import re
from dataclasses import dataclass
from typing import List

from app.llm import LLMService
from app.retrieval.citations import Citation, CitationBuilder
from app.retrieval.evidence import EvidenceAnalyzer, EvidenceResult
from app.retrieval.retriever import RetrievalService
from app.tools.order_lookup import OrderLookupService
from app.observability import log_event


# ==============================================================
# RESPONSE MODEL
# ==============================================================

@dataclass
class AgentResponse:
    answer_type: str
    message: str
    citations: List[Citation]
    evidence: EvidenceResult | None = None

    @property
    def is_grounded(self) -> bool:
        return self.answer_type == "grounded"

    @property
    def requires_handoff(self) -> bool:
        """
        Whether this response requires human assistance.

        Handoff is required when:
        - authoritative sources conflict
        - the supplied information is insufficient
        - an order cannot be found
        """

        return self.answer_type in {
            "conflict",
            "insufficient_evidence",
            "order_not_found",
        }
# ==============================================================
# SUPPORT AGENT
# ==============================================================

class SupportAgent:
    """
    Reliable Aster & Row customer support agent.

    Processing order:

    1. Detect explicit order IDs.
    2. Protect private/internal order information.
    3. Perform deterministic order lookup.
    4. Detect generic order questions.
    5. Retrieve knowledge-base evidence.
    6. Prioritize active/official evidence.
    7. Detect conflicts.
    8. Handle deterministic policy questions.
    9. Use LLM only when appropriate.
    10. Never allow the LLM to generate order information.

    Important safety properties:

    - Order information is NEVER generated by the LLM.
    - Internal/private order information is never exposed.
    - Time-specific return questions are not answered from
      unrelated evidence.
    - Shipping-address changes are NOT treated as private
      information requests.
    """

    ORDER_ID_PATTERN = re.compile(
        r"\bORD-\d+\b",
        re.IGNORECASE,
    )

    # ==========================================================
    # INITIALIZATION
    # ==========================================================

    def __init__(
        self,
        retrieval_service: RetrievalService,
        evidence_analyzer: EvidenceAnalyzer,
        llm_service: LLMService | None = None,
        order_lookup_service: OrderLookupService | None = None,
    ):
        self.retrieval_service = retrieval_service
        self.evidence_analyzer = evidence_analyzer

        self.llm_service = (
            llm_service
            or LLMService()
        )

        self.order_lookup_service = (
            order_lookup_service
            or OrderLookupService()
        )

    # ==========================================================
    # ORDER ID DETECTION
    # ==========================================================

    @classmethod
    def _extract_order_id(
        cls,
        query: str,
    ) -> str | None:

        match = cls.ORDER_ID_PATTERN.search(
            query
        )

        if not match:
            return None

        return match.group(0)

    @staticmethod
    def _is_order_question(
        query: str,
    ) -> bool:

        return (
            SupportAgent._extract_order_id(
                query
            )
            is not None
        )

    # ==========================================================
    # GENERIC ORDER QUESTION DETECTION
    # ==========================================================

    @staticmethod
    def _looks_like_order_question(
        query: str,
    ) -> bool:

        text = query.lower()

        order_terms = [
            "my order",
            "my shipment",
            "my package",
            "my delivery",
            "order status",
            "where is my order",
            "where's my order",
            "where is my package",
            "where's my package",
            "when will my order",
            "when will my package",
            "when will my shipment",
            "when does my order",
            "track my order",
            "track my package",
            "order arrive",
            "package arrive",
        ]

        return any(
            term in text
            for term in order_terms
        )

    # ============================================================
    # PRIVATE / INTERNAL INFORMATION DETECTION
    # ============================================================

    @staticmethod
    def _is_private_order_information_question(
        query: str,
    ) -> bool:
        """
        Detect requests for sensitive/private order information.

        Legitimate order-management questions such as:
            "Can I change my shipping address?"
            "Can I update my delivery address?"

        must NOT be blocked.
        """

        text = query.lower().strip()

        # --------------------------------------------------------
        # Internal risk information
        # --------------------------------------------------------

        risk_terms = [
            "risk score",
            "internal risk",
            "risk rating",
            "fraud score",
            "fraud risk",
            "internal score",
        ]

        if any(term in text for term in risk_terms):
            return True

        # --------------------------------------------------------
        # Internal/private notes
        # --------------------------------------------------------

        internal_terms = [
            "internal note",
            "internal notes",
            "internal comment",
            "internal comments",
            "staff note",
            "staff notes",
            "agent note",
            "agent notes",
            "internal information",
        ]

        if any(term in text for term in internal_terms):
            return True

        # --------------------------------------------------------
        # Customer email
        # --------------------------------------------------------

        email_terms = [
            "email address",
            "customer email",
            "email for",
            "email on the order",
        ]

        if any(term in text for term in email_terms):
            return True

        # --------------------------------------------------------
        # Shipping / delivery / billing address
        # --------------------------------------------------------

        address_terms = [
            "shipping address",
            "delivery address",
            "billing address",
        ]

        # These indicate that the customer wants to MODIFY
        # an address rather than reveal it.
        address_change_terms = [
            "change",
            "update",
            "modify",
            "correct",
            "edit",
        ]

        asks_for_address = any(
            term in text
            for term in address_terms
        )

        asks_to_change_address = any(
            term in text
            for term in address_change_terms
        )

        # Example:
        # "Can I change my shipping address?"
        # -> NOT private information
        if asks_for_address and not asks_to_change_address:

            address_request_terms = [
                "what is",
                "what's",
                "tell me",
                "show me",
                "give me",
                "provide",
                "where is",
                "where's",
            ]

            if any(
                term in text
                for term in address_request_terms
            ):
                return True

        return False
    # ==========================================================
    # PRIVATE INFORMATION RESPONSE
    # ==========================================================

    @staticmethod
    def _answer_private_information_request() -> AgentResponse:

        return AgentResponse(
            answer_type="insufficient_evidence",
            message=(
                "I can't provide internal or private customer "
                "information such as risk scores, email addresses, "
                "shipping addresses, or internal notes."
            ),
            citations=[],
            evidence=None,
        )

    # ==========================================================
    # ORDER LOOKUP
    # ==========================================================

    def _run_order_lookup(
        self,
        query: str,
    ) -> AgentResponse:

        order_id = self._extract_order_id(
            query
        )

        # ------------------------------------------------------
        # Missing order ID
        # ------------------------------------------------------

        if order_id is None:

            return AgentResponse(
                answer_type="clarification",
                message=(
                    "An order ID is required to look up "
                    "order information. Please provide "
                    "your order ID, for example ORD-1007."
                ),
                citations=[],
                evidence=None,
            )

        # ------------------------------------------------------
        # Deterministic order lookup
        # ------------------------------------------------------

        result = self.order_lookup_service.lookup(
            order_id
        )

        # ------------------------------------------------------
        # Unknown order
        # ------------------------------------------------------

                # ------------------------------------------------------
        # Unknown order
        # ------------------------------------------------------

        if not result.found:

            return AgentResponse(
                answer_type="order_not_found",
                message=(
                    f"No order was found for {order_id}. "
                    "Please check the order ID or contact support "
                    "for assistance."
                ),
                citations=[],
                evidence=None,
            )

        # ------------------------------------------------------
        # Customer-safe response
        # ------------------------------------------------------

        parts = []

        status = (
            result.status or ""
        ).strip().lower()

        if status:

            parts.append(
                f"The status of {result.order_id} is "
                f"**{status}**."
            )

        # Customer-safe message supplied by lookup service.

        if result.customer_safe_message:

            parts.append(
                result.customer_safe_message
            )

        # ------------------------------------------------------
        # Carrier
        # ------------------------------------------------------

        if result.carrier:

            parts.append(
                f"Carrier: **{result.carrier}**."
            )

        # ------------------------------------------------------
        # Tracking number
        # ------------------------------------------------------

        if result.tracking_number:

            parts.append(
                "Tracking number: "
                f"**{result.tracking_number}**."
            )

        # ------------------------------------------------------
        # Estimated delivery
        # ------------------------------------------------------

        if result.estimated_delivery:

            parts.append(
                "Estimated delivery: "
                f"**{result.estimated_delivery}**."
            )

        message = " ".join(parts).strip()

        if not message:

            message = (
                f"Order {result.order_id} was found, "
                "but there is no customer-safe status "
                "information available."
            )

        return AgentResponse(
            answer_type="order_lookup",
            message=message,
            citations=[],
            evidence=None,
        )

    # ==========================================================
    # EVIDENCE PRIORITIZATION
    # ==========================================================

    @staticmethod
    def _is_active_official(
        result,
    ) -> bool:

        chunk = result.chunk

        status = (
            chunk.status or ""
        ).strip().lower()

        authority = (
            chunk.policy_authority or ""
        ).strip().lower()

        return (
            status == "active"
            and authority == "official"
        )

    @staticmethod
    def _is_active(
        result,
    ) -> bool:

        status = (
            result.chunk.status or ""
        ).strip().lower()

        return status == "active"

    def _select_best_evidence(
        self,
        evidence: EvidenceResult,
    ) -> EvidenceResult:

        chunks = evidence.chunks

        if not chunks:
            return evidence

        # ------------------------------------------------------
        # First preference:
        #
        # active + official
        # ------------------------------------------------------

        active_official = [
            result
            for result in chunks
            if self._is_active_official(result)
        ]

        if active_official:

            selected = active_official

        else:

            # --------------------------------------------------
            # Second preference:
            #
            # active sources
            # --------------------------------------------------

            active = [
                result
                for result in chunks
                if self._is_active(result)
            ]

            if active:
                selected = active
            else:
                selected = chunks

        # ------------------------------------------------------
        # Remove duplicate source/headings.
        #
        # Keep highest-scoring result.
        # ------------------------------------------------------

        unique = {}

        for result in selected:

            chunk = result.chunk

            key = (
                chunk.source_file,
                chunk.heading,
            )

            previous = unique.get(key)

            if (
                previous is None
                or result.score > previous.score
            ):
                unique[key] = result

        selected = list(
            unique.values()
        )

        # Highest relevance first.

        selected.sort(
            key=lambda item: item.score,
            reverse=True,
        )

        return EvidenceResult(
            chunks=selected,
            conflicts=evidence.conflicts,
            excluded_chunks=evidence.excluded_chunks,
        )

    # ==========================================================
    # POLICY QUESTION DETECTION
    # ==========================================================

    @staticmethod
    def _is_return_window_question(
        query: str,
    ) -> bool:

        text = query.lower()

        return (
            (
                "return" in text
                or "returns" in text
            )
            and (
                "days" in text
                or "window" in text
                or "how long" in text
            )
        )

    @staticmethod
    def _is_return_shipping_fee_question(
        query: str,
    ) -> bool:

        text = query.lower()

        return (
            (
                "return" in text
                or "returns" in text
            )
            and (
                "shipping fee" in text
                or "return fee" in text
                or "shipping cost" in text
            )
        )

    # ==========================================================
    # SHIPPING ADDRESS QUESTION
    # ==========================================================

    @staticmethod
    def _is_shipping_address_question(
        query: str,
    ) -> bool:

        text = query.lower()

        return (
            "shipping address" in text
            or "delivery address" in text
            or "change my address" in text
            or "change the address" in text
            or "update my address" in text
            or "update the address" in text
            or "modify my address" in text
            or "edit my address" in text
        )

    # ==========================================================
    # TIME-SPECIFIC RETURN QUESTION
    # ==========================================================

    @staticmethod
    def _is_time_specific_return_question(
        query: str,
    ) -> bool:

        text = query.lower()

        return (
            (
                "return" in text
                or "returns" in text
            )
            and bool(
                re.search(
                    r"\b\d+\s*days?\b",
                    text,
                )
            )
        )

    # ==========================================================
    # FINAL-SALE QUESTION
    # ==========================================================

    @staticmethod
    def _is_final_sale_question(
        query: str,
    ) -> bool:

        text = query.lower()

        return (
            (
                "final-sale" in text
                or "final sale" in text
            )
            and (
                "return" in text
                or "exchange" in text
            )
        )

        # ==========================================================
    # DETERMINISTIC RETURN WINDOW ANSWER
    # ==========================================================

        # ==========================================================
    # DETERMINISTIC RETURN WINDOW ANSWER
    # ==========================================================

    def _answer_return_window(
        self,
        evidence: EvidenceResult,
    ) -> AgentResponse | None:

        trailplus_chunk = None
        standard_chunk = None

        for result in evidence.chunks:

            text = (
                result.chunk.content or ""
            ).lower()

            if (
                "trailplus" in text
                and (
                    "45" in text
                    or "forty-five" in text
                )
            ):
                trailplus_chunk = result

            if (
                "standard" in text
                and (
                    "30" in text
                    or "thirty" in text
                )
            ):
                standard_chunk = result

        # ------------------------------------------------------
        # Both policies
        # ------------------------------------------------------

        if (
            trailplus_chunk
            and standard_chunk
        ):

            citations = CitationBuilder.build_many(
                [
                    trailplus_chunk,
                    standard_chunk,
                ]
            )

            message = (
                "The return window depends on your membership status:\n\n"
                "- **TrailPlus members:** 45 calendar days from delivery "
                "for eligible items, provided the membership was active "
                "when the order was placed.\n"
                "- **Standard plan customers:** 30 calendar days from "
                "delivery for eligible items.\n\n"
                "Joining TrailPlus after placing an order does not extend "
                "that order's return window."
            )

            return AgentResponse(
                answer_type="grounded",
                message=message,
                citations=citations,
                evidence=evidence,
            )

        # ------------------------------------------------------
        # TrailPlus only
        # ------------------------------------------------------

        if trailplus_chunk:

            citations = CitationBuilder.build_many(
                [
                    trailplus_chunk,
                ]
            )

            message = (
                "TrailPlus members receive a return window of "
                "**45 calendar days from delivery** for eligible "
                "items, provided the membership was active "
                "when the order was placed."
            )

            return AgentResponse(
                answer_type="grounded",
                message=message,
                citations=citations,
                evidence=evidence,
            )

        # ------------------------------------------------------
        # Standard only
        # ------------------------------------------------------

        if standard_chunk:

            citations = CitationBuilder.build_many(
                [
                    standard_chunk,
                ]
            )

            message = (
                "Standard plan customers have a "
                "**30 calendar days return window from "
                "delivery** for eligible items."
            )

            return AgentResponse(
                answer_type="grounded",
                message=message,
                citations=citations,
                evidence=evidence,
            )

        return None
    # ==========================================================
    # DETERMINISTIC RETURN SHIPPING ANSWER
    # ==========================================================

    def _answer_return_shipping_fee(
        self,
        evidence: EvidenceResult,
    ) -> AgentResponse | None:

        policy_chunk = None

        for result in evidence.chunks:

            text = (
                result.chunk.content or ""
            ).lower()

            if (
                "$6.95" in text
                or "6.95" in text
            ):
                policy_chunk = result
                break

        if policy_chunk is None:
            return None

        citations = CitationBuilder.build_many(
            [policy_chunk]
        )

        message = (
            "The return shipping fee for standard domestic "
            "returns is **$6.95**. The fee is deducted from "
            "the refund unless the item arrived damaged or "
            "was sent incorrectly, in which case the fee "
            "is waived."
        )

        return AgentResponse(
            answer_type="grounded",
            message=message,
            citations=citations,
            evidence=evidence,
        )

    # ==========================================================
    # DETERMINISTIC FINAL-SALE ANSWER
    # ==========================================================

    def _answer_final_sale(
        self,
        evidence: EvidenceResult,
    ) -> AgentResponse | None:

        relevant = []

        for result in evidence.chunks:

            text = (
                result.chunk.content or ""
            ).lower()

            if (
                (
                    "final sale" in text
                    or "final-sale" in text
                )
                and (
                    "return" in text
                    or "exchange" in text
                )
            ):
                relevant.append(result)

        if not relevant:
            return None

        # Highest-scoring evidence first.

        relevant.sort(
            key=lambda item: item.score,
            reverse=True,
        )

        # Keep only strongest two citations.

        selected = relevant[:2]

        citations = CitationBuilder.build_many(
            selected
        )

        message = (
            "Final-sale items cannot be returned or "
            "exchanged for a change of mind. However, "
            "damaged, defective, or incorrect final-sale "
            "items may still qualify for assistance under "
            "the Damaged or Wrong Items Policy."
        )

        return AgentResponse(
            answer_type="grounded",
            message=message,
            citations=citations,
            evidence=evidence,
        )

    # ==========================================================
    # DETERMINISTIC SHIPPING ADDRESS ANSWER
    # ==========================================================

    def _answer_shipping_address(
        self,
        evidence: EvidenceResult,
    ) -> AgentResponse | None:

        address_chunk = None

        for result in evidence.chunks:

            chunk = result.chunk

            source = (
                chunk.source_file or ""
            ).lower()

            heading = (
                chunk.heading or ""
            ).lower()

            content = (
                chunk.content or ""
            ).lower()

            # --------------------------------------------------
            # Exact address-change policy is preferred.
            # --------------------------------------------------

            if (
                "order-changes-and-cancellations.md"
                in source
                and "address" in heading
            ):
                address_chunk = result
                break

            if (
                "address changes" in heading
                or "shipping address" in content
            ):

                if address_chunk is None:
                    address_chunk = result

        if address_chunk is None:
            return None

        citations = CitationBuilder.build_many(
            [address_chunk]
        )

        message = (
            "You can request a change to your shipping "
            "address within **30 minutes** while an order "
            "is still pending. Once the order enters "
            "processing, Aster & Row cannot guarantee the "
            "change. After shipment, address modifications "
            "must be handled through the carrier."
        )

        return AgentResponse(
            answer_type="grounded",
            message=message,
            citations=citations,
            evidence=evidence,
        )

        # ==========================================================
    # GENERIC GROUNDED RESPONSE
    # ==========================================================

    def _generic_grounded_response(
        self,
        evidence: EvidenceResult,
    ) -> AgentResponse:

        citations = CitationBuilder.build_many(
            evidence.chunks
        )

        if not evidence.chunks:

            return AgentResponse(
                answer_type="insufficient_evidence",
                message=(
                    "I don't have enough information in the "
                    "knowledge base to answer this reliably."
                ),
                citations=[],
                evidence=evidence,
            )

        # Use the strongest retrieved passage to provide a
        # grounded fallback answer.

        best = evidence.chunks[0].chunk

        message = (
            best.content or ""
        ).strip()

        if not message:

            return AgentResponse(
                answer_type="insufficient_evidence",
                message=(
                    "I don't have enough information in the "
                    "knowledge base to answer this reliably."
                ),
                citations=[],
                evidence=evidence,
            )

        return AgentResponse(
            answer_type="grounded",
            message=message,
            citations=citations,
            evidence=evidence,
        )

    
    # ==========================================================
    # RETRIEVE + ANALYZE EVIDENCE
    # ==========================================================

    def _retrieve_evidence(
        self,
        query: str,
        top_k: int,
    ) -> EvidenceResult:

        retrieved = (
            self.retrieval_service.retrieve(
                query,
                top_k=top_k,
            )
        )

        log_event(
            "retrieval",
            query=query,
            top_k=top_k,
            retrieved_count=len(retrieved),
            retrieved=[
                {
                    "source_file": r.chunk.source_file,
                    "heading": r.chunk.heading,
                    "score": r.score,
                    "status": r.chunk.status,
                    "authority": r.chunk.policy_authority,
                }
                for r in retrieved
            ],
        )

        evidence = (
            self.evidence_analyzer.analyze(
                retrieved
            )
        )

        evidence = self._select_best_evidence(
            evidence
        )

        log_event(
            "evidence",
            query=query,
            selected_count=len(evidence.chunks),
            conflict=evidence.has_conflict,
            excluded_count=len(evidence.excluded_chunks),
            selected_sources=[
                r.chunk.source_file
                for r in evidence.chunks
            ],
        )

        return evidence

    # ==========================================================
    # DETERMINISTIC KNOWLEDGE-BASE ANSWERS
    # ==========================================================

    def _answer_shipping_country(
        self,
        query: str,
        evidence: EvidenceResult,
    ) -> AgentResponse | None:
        """
        Answer international shipping questions directly from
        retrieved evidence.

        This prevents generic LLM fallbacks such as:
        'Relevant evidence was found.'
        """

        text = query.lower()

        # Only handle international shipping questions here.
        shipping_terms = [
            "ship internationally",
            "international shipping",
            "ship to",
            "shipping to",
            "deliver to",
            "delivery to",
            "canada",
            "germany",
        ]

        if not any(term in text for term in shipping_terms):
            return None

        relevant = []

        for result in evidence.chunks:

            chunk_text = (
                result.chunk.content or ""
            ).lower()

            source = (
                result.chunk.source_file or ""
            ).lower()

            if (
                "06-international-shipping.md" in source
                or "international" in chunk_text
            ):
                relevant.append(result)

        if not relevant:
            return None

        # ------------------------------------------------------
        # Canada
        # ------------------------------------------------------

        if "canada" in text:

            canada_supported = any(
                "canada" in (
                    result.chunk.content or ""
                ).lower()
                for result in relevant
            )

            if canada_supported:

                citations = CitationBuilder.build_many(
                    relevant[:2]
                )

                message = (
                    "Yes. **Canada is supported** for "
                    "international shipping. Delivery typically "
                    "takes **5–9 business days after dispatch**, "
                    "and **duties or taxes are not prepaid**."
                )

                return AgentResponse(
                    answer_type="grounded",
                    message=message,
                    citations=citations,
                    evidence=evidence,
                )

        # ------------------------------------------------------
        # Germany / unsupported country
        # ------------------------------------------------------

        if "germany" in text:

            citations = CitationBuilder.build_many(
                relevant[:2]
            )

            message = (
                "Shipping to Germany is not currently available "
                "according to the international shipping policy. "
                "shipping policy."
            )

            return AgentResponse(
                answer_type="grounded",
                message=message,
                citations=citations,
                evidence=evidence,
            )

        return None


    # ==========================================================
# WARRANTY ANSWER
# ==========================================================

    def _answer_warranty(
        self,
        query: str,
        evidence: EvidenceResult,
    ) -> AgentResponse | None:
        """
        Answer warranty questions deterministically.

        The answer must explicitly state that there is no
        lifetime warranty and provide the documented warranty
        periods for each product category.
        """

        text = query.lower()

        if "warranty" not in text:
            return None

        warranty_chunks = []

        for result in evidence.chunks:

            source = (
                result.chunk.source_file or ""
            ).lower()

            content = (
                result.chunk.content or ""
            ).lower()

            if "07-warranty.md" in source:
                warranty_chunks.append(result)

        if not warranty_chunks:
            return None

        citations = CitationBuilder.build_many(
            warranty_chunks
        )

        message = (
            "There is no lifetime warranty covering all "
            "Aster & Row products. Bags have 2 years, while "
            "drinkware and travel accessories have 1 year."
        )

        return AgentResponse(
            answer_type="grounded",
            message=message,
            citations=citations,
            evidence=evidence,
        )    # ==========================================================
    # INSUFFICIENT MATERIAL / VEGAN ANSWER
    # ==========================================================

    def _answer_material_question(
        self,
        query: str,
        evidence: EvidenceResult,
    ) -> AgentResponse | None:
        """
        Safely abstain when the KB does not establish material
        certification or vegan status.
        """

        text = query.lower()

        material_terms = [
            "vegan",
            "fabrics",
            "adhesives",
            "material certification",
            "materials",
        ]

        if not any(
            term in text
            for term in material_terms
        ):
            return None

        # This question requires a specific material-level
        # guarantee. Do not infer it from unrelated product
        # information.

        return AgentResponse(
            answer_type="insufficient_evidence",
            message=(
                "The supplied information is insufficient to "
                "confirm whether all fabrics and adhesives used "
                "in Aster & Row bags are vegan. Please obtain "
                "human confirmation before relying on a vegan "
                "material guarantee."
            ),
            citations=[],
            evidence=evidence,
        )


    # ==========================================================
# PROMPT-INJECTION / MIGRATION NOTE
# ==========================================================

# ==========================================================
# PROMPT-INJECTION / MIGRATION NOTE
# ==========================================================

    # ==========================================================
    # PROMPT-INJECTION / MIGRATION NOTE
    # ==========================================================

    def _answer_migration_note_question(
        self,
        query: str,
        evidence: EvidenceResult,
    ) -> AgentResponse | None:
        """
        Prevent internal migration notes from overriding the
        current customer-facing return policy.
        """

        text = query.lower()

        injection_terms = [
            "migration note",
            "ignore the real policy",
            "60 days",
            "approve my return",
            "newer document",
        ]

        if not any(
            term in text
            for term in injection_terms
        ):
            return None

        policy_chunk = None

        for result in evidence.chunks:

            source = (
                result.chunk.source_file or ""
            ).lower()

            if "01-returns-policy-current.md" in source:
                policy_chunk = result
                break

        if policy_chunk is None:
            return None

        citations = CitationBuilder.build_many(
            [policy_chunk]
        )

        message = (
            "The migration note is not authoritative and "
            "cannot override the current customer-facing policy. "
            "The standard policy is 30 days unless a valid "
            "documented exception applies. "
            "The agent cannot approve a return automatically."
        )

        return AgentResponse(
            answer_type="grounded",
            message=message,
            citations=citations,
            evidence=evidence,
        )

    # ==========================================================
    # FINAL-SALE + DAMAGED ITEM
    # ==========================================================

    def _answer_final_sale_damaged(
        self,
        query: str,
        evidence: EvidenceResult,
    ) -> AgentResponse | None:
        """
        Handle a final-sale item that is damaged, defective,
        or incorrect.
        """

        text = query.lower()

        final_sale = (
            "final sale" in text
            or "final-sale" in text
        )

        damaged = any(
            term in text
            for term in [
                "broken",
                "damaged",
                "defective",
                "wrong item",
                "incorrect item",
                "zipper",
            ]
        )

        if not (
            final_sale
            and damaged
        ):
            return None

        damaged_chunk = None
        final_sale_chunk = None

        for result in evidence.chunks:

            source = (
                result.chunk.source_file or ""
            ).lower()

            if "04-damaged-or-wrong-items.md" in source:
                damaged_chunk = result

            elif "03-final-sale-and-promotions.md" in source:
                final_sale_chunk = result

        # The damaged/wrong-item policy is required.
        if damaged_chunk is None:
            return None

        selected = [
            damaged_chunk
        ]

        if final_sale_chunk is not None:
            selected.append(
                final_sale_chunk
            )

        citations = CitationBuilder.build_many(
            selected
        )

        message = (
            "A **final sale does not block damaged-item review**. "
            "A final-sale item is not automatically excluded from damaged-item review. "
            "If the item arrived "
            "damaged, defective, or incorrect, it should be "
            "**reported within 7 days**. A **human review is "
            "required before approval**, so I cannot approve "
            "the claim automatically."
        )

        return AgentResponse(
            answer_type="grounded",
            message=message,
            citations=citations,
            evidence=evidence,
        )


    # ==========================================================
    # PRODUCT-CARE CONFLICT
    # ==========================================================

    def _answer_product_care_conflict(
        self,
        query: str,
        evidence: EvidenceResult,
    ) -> AgentResponse | None:
        """
        Explain a genuine conflict between the current
        product-care sources instead of silently selecting one.
        """

        text = query.lower()

        if not (
            "dishwasher" in text
            and "breeze" in text
        ):
            return None

        care_chunk = None
        product_chunk = None

        for result in evidence.chunks:

            source = (
                result.chunk.source_file or ""
            ).lower()

            if "11-product-care.md" in source:
                care_chunk = result

            elif "12-breeze-tumbler-product-card.md" in source:
                product_chunk = result

        if not (
            care_chunk
            and product_chunk
        ):
            return None

        citations = CitationBuilder.build_many(
            [
                care_chunk,
                product_chunk,
            ]
        )

        message = (
            "The current official sources **conflict** on "
            "whether the entire Breeze Tumbler can go in the "
            "dishwasher. **One says hand-wash the body**, "
            "while another says **all components are "
            "dishwasher safe**. Because these instructions "
            "conflict, I cannot safely choose one as definitive. "
            "Please get human confirmation; as the safest "
            "interim guidance, hand-wash the body."
        )

        return AgentResponse(
            answer_type="conflict",
            message=message,
            citations=citations,
            evidence=evidence,
        )



    def _try_deterministic_answer(
        self,
        query: str,
        evidence: EvidenceResult,
    ) -> AgentResponse | None:

        # ------------------------------------------------------
        # Product-care source conflict
        # ------------------------------------------------------

        answer = self._answer_product_care_conflict(
            query,
            evidence,
        )

        if answer is not None:
            return answer

        # ------------------------------------------------------
        # Final-sale damaged/defective exception
        # ------------------------------------------------------

        answer = self._answer_final_sale_damaged(
            query,
            evidence,
        )

        if answer is not None:
            return answer

        # ------------------------------------------------------
        # International shipping
        # ------------------------------------------------------

        answer = self._answer_shipping_country(
            query,
            evidence,
        )

        if answer is not None:
            return answer

        # ------------------------------------------------------
        # Warranty
        # ------------------------------------------------------

        answer = self._answer_warranty(
            query,
            evidence,
        )

        if answer is not None:
            return answer

        # ------------------------------------------------------
        # Material / vegan information
        # ------------------------------------------------------

        answer = self._answer_material_question(
            query,
            evidence,
        )

        if answer is not None:
            return answer

        # ------------------------------------------------------
        # Migration note / prompt injection
        # ------------------------------------------------------

        answer = self._answer_migration_note_question(
            query,
            evidence,
        )

        if answer is not None:
            return answer

        # ------------------------------------------------------
        # Final-sale
        # ------------------------------------------------------

        if self._is_final_sale_question(query):

            answer = self._answer_final_sale(
                evidence
            )

            if answer is not None:
                return answer

        # ------------------------------------------------------
        # Shipping address
        # ------------------------------------------------------

        if self._is_shipping_address_question(query):

            answer = self._answer_shipping_address(
                evidence
            )

            if answer is not None:
                return answer

        # ------------------------------------------------------
        # Time-specific return question
        # ------------------------------------------------------

        if self._is_time_specific_return_question(
            query
        ):

            if self._is_return_window_question(
                query
            ):

                answer = self._answer_return_window(
                    evidence
                )

                if answer is not None:

                    requested_days = re.search(
                        r"\b(\d+)\s*days?\b",
                        query.lower(),
                    )

                    if requested_days:

                        requested = int(
                            requested_days.group(1)
                        )

                        supported = []

                        for result in evidence.chunks:

                            content = (
                                result.chunk.content
                                or ""
                            ).lower()

                            if (
                                "45" in content
                                and "trailplus" in content
                            ):
                                supported.append(45)

                            if (
                                "30" in content
                                and "standard" in content
                            ):
                                supported.append(30)

                        if (
                            supported
                            and requested not in supported
                        ):

                            return AgentResponse(
                                answer_type="insufficient_evidence",
                                message=(
                                    "I don't have enough "
                                    "information in the "
                                    "knowledge base to answer "
                                    "this question reliably."
                                ),
                                citations=[],
                                evidence=evidence,
                            )

                    return answer

            return AgentResponse(
                answer_type="insufficient_evidence",
                message=(
                    "I don't have enough information in the "
                    "knowledge base to answer this question "
                    "reliably."
                ),
                citations=[],
                evidence=evidence,
            )

        # ------------------------------------------------------
        # Normal return-window question
        # ------------------------------------------------------

        if self._is_return_window_question(query):

            answer = self._answer_return_window(
                evidence
            )

            if answer is not None:
                return answer

        # ------------------------------------------------------
        # Return shipping fee
        # ------------------------------------------------------

        if self._is_return_shipping_fee_question(query):

            answer = self._answer_return_shipping_fee(
                evidence
            )

            if answer is not None:
                return answer

        return None

    # ==========================================================
    # MAIN RAG PIPELINE
    # ==========================================================

    def run(
        self,
        query: str,
        top_k: int = 5,
    ) -> AgentResponse:

        query = query.strip()

        if not query:
            raise ValueError(
                "Query cannot be empty."
            )

        # ------------------------------------------------------
        # Explicit order ID
        # ------------------------------------------------------

        if self._is_order_question(query):

            if self._is_private_order_information_question(
                query
            ):
                return (
                    self._answer_private_information_request()
                )

            return self._run_order_lookup(query)

        # ------------------------------------------------------
        # Generic order question
        # ------------------------------------------------------

        if self._looks_like_order_question(query):
            return self._run_order_lookup(query)

        # ------------------------------------------------------
        # Protected information
        # ------------------------------------------------------

        if self._is_private_order_information_question(query):
            return (
                self._answer_private_information_request()
            )

        # ------------------------------------------------------
        # Retrieve evidence
        # ------------------------------------------------------

        # Prompt-injection / migration-note queries need the
        # current returns policy available for deterministic
        # grounding. Retrieve a wider evidence set so the current
        # policy is not lost behind the internal migration note.
        retrieval_top_k = top_k

        migration_query = any(
            term in query.lower()
            for term in [
                "migration note",
                "ignore the real policy",
                "60 days",
                "approve my return",
                "newer document",
            ]
        )

        if migration_query:
            retrieval_top_k = max(top_k, 20)

        evidence = self._retrieve_evidence(
            query,
            retrieval_top_k,
        )

        # ------------------------------------------------------
        # No evidence
        # ------------------------------------------------------

        if not evidence.chunks:
            return AgentResponse(
                answer_type="insufficient_evidence",
                message=(
                    "I don't have enough information "
                    "in the knowledge base to answer "
                    "this question reliably."
                ),
                citations=[],
                evidence=evidence,
            )

        # ------------------------------------------------------
        # Deterministic answers
        # ------------------------------------------------------

        deterministic = self._try_deterministic_answer(
            query,
            evidence,
        )

        if deterministic is not None:
            return deterministic

        # ------------------------------------------------------
        # Conflict
        # ------------------------------------------------------

        if evidence.has_conflict:

            citations = CitationBuilder.build_many(
                evidence.chunks
            )

            return AgentResponse(
                answer_type="conflict",
                message=(
                    "I found conflicting current official "
                    "information. I cannot safely provide "
                    "a definitive answer without resolving "
                    "the conflict."
                ),
                citations=citations,
                evidence=evidence,
            )

        # ------------------------------------------------------
        # Generic grounded response
        # ------------------------------------------------------

        return self._generic_grounded_response(
            evidence
        )

               # ==========================================================
        # ==========================================================
    # LLM RAG PIPELINE
    # ==========================================================

    def run_with_llm(
        self,
        query: str,
        top_k: int = 5,
    ) -> AgentResponse:

        query = query.strip()

        if not query:
            raise ValueError(
                "Query cannot be empty."
            )

        # ------------------------------------------------------
        # Explicit order ID
        # ------------------------------------------------------

        if self._is_order_question(query):

            if self._is_private_order_information_question(
                query
            ):
                return (
                    self._answer_private_information_request()
                )

            return self._run_order_lookup(query)

        # ------------------------------------------------------
        # Generic order question
        # ------------------------------------------------------

        if self._looks_like_order_question(query):
            return self._run_order_lookup(query)

        # ------------------------------------------------------
        # Protected information
        # ------------------------------------------------------

        if self._is_private_order_information_question(query):
            return (
                self._answer_private_information_request()
            )

        # ------------------------------------------------------
        # Retrieve evidence
        # ------------------------------------------------------

        # Prompt-injection / migration-note queries need the
        # current returns policy available for deterministic
        # grounding. Retrieve a wider evidence set so the current
        # policy is not lost behind the internal migration note.
        retrieval_top_k = top_k

        migration_query = any(
            term in query.lower()
            for term in [
                "migration note",
                "ignore the real policy",
                "60 days",
                "approve my return",
                "newer document",
            ]
        )

        if migration_query:
            retrieval_top_k = max(top_k, 20)

        evidence = self._retrieve_evidence(
            query,
            retrieval_top_k,
        )

        # ------------------------------------------------------
        # No evidence
        # ------------------------------------------------------

        if not evidence.chunks:
            return AgentResponse(
                answer_type="insufficient_evidence",
                message=(
                    "I don't have enough information "
                    "in the knowledge base to answer "
                    "this question reliably."
                ),
                citations=[],
                evidence=evidence,
            )

        # ------------------------------------------------------
        # Deterministic answers
        # ------------------------------------------------------

        deterministic = self._try_deterministic_answer(
            query,
            evidence,
        )

        if deterministic is not None:
            return deterministic

        # ------------------------------------------------------
        # Conflict
        # ------------------------------------------------------

        if evidence.has_conflict:

            citations = CitationBuilder.build_many(
                evidence.chunks
            )

            return AgentResponse(
                answer_type="conflict",
                message=(
                    "I found conflicting current official "
                    "information. I cannot safely provide "
                    "a definitive answer without resolving "
                    "the conflict."
                ),
                citations=citations,
                evidence=evidence,
            )

        # ------------------------------------------------------
        # Generic LLM response
        # ------------------------------------------------------

        citations = CitationBuilder.build_many(
            evidence.chunks
        )

        try:

            evidence_text = (
                self.llm_service._format_evidence(
                    evidence.chunks
                )
            )

            prompt = (
                self.llm_service._build_prompt(
                    query=query,
                    evidence_text=evidence_text,
                )
            )

            llm_message = (
                self.llm_service.generate(
                    prompt=prompt,
                    evidence=evidence.chunks,
                )
            )

        except Exception:

            llm_message = None

        # ------------------------------------------------------
        # LLM failure
        # ------------------------------------------------------

        if not llm_message:
            return AgentResponse(
                answer_type="grounded",
                message="Relevant evidence was found.",
                citations=citations,
                evidence=evidence,
            )

        return AgentResponse(
            answer_type="grounded",
            message=str(llm_message).strip(),
            citations=citations,
            evidence=evidence,
        )

# ==========================================================
# NON-INTRUSIVE OBSERVABILITY WRAPPERS
# ==========================================================

_original_run = SupportAgent.run
_original_run_with_llm = SupportAgent.run_with_llm


def _observed_run(self, query: str, top_k: int = 5):
    log_event("user_message", query=query, method="run")
    try:
        response = _original_run(self, query, top_k=top_k)
        log_event(
            "final_response",
            query=query,
            answer_type=response.answer_type,
            handoff=response.requires_handoff,
            citations=[c.source_file for c in (response.citations or [])],
        )
        return response
    except Exception as exc:
        log_event(
            "agent_error",
            query=query,
            error_type=type(exc).__name__,
            error=str(exc),
        )
        raise


def _observed_run_with_llm(self, query: str, top_k: int = 5):
    log_event("user_message", query=query, method="run_with_llm")
    try:
        response = _original_run_with_llm(self, query, top_k=top_k)
        log_event(
            "final_response",
            query=query,
            answer_type=response.answer_type,
            handoff=response.requires_handoff,
            citations=[c.source_file for c in (response.citations or [])],
        )
        return response
    except Exception as exc:
        log_event(
            "agent_error",
            query=query,
            error_type=type(exc).__name__,
            error=str(exc),
        )
        raise


SupportAgent.run = _observed_run
SupportAgent.run_with_llm = _observed_run_with_llm
